-- 042_add_client_request_id_for_idempotency.sql
-- Add client_request_id (UUID) to work_orders and movements to enable
-- per-submission idempotency. The frontend will generate a UUID on each
-- Submit click and pass it to the RPC; the database UNIQUE index prevents
-- the same submission from creating two rows even under retries or races.
--
-- This is purely additive (NULL allowed for historical rows).
-- A subsequent migration (047) will backfill UUIDs for existing rows.

BEGIN;

-- 1) work_orders.client_request_id
ALTER TABLE public.work_orders
  ADD COLUMN IF NOT EXISTS client_request_id UUID;

COMMENT ON COLUMN public.work_orders.client_request_id IS
  'Per-submission UUID generated by the client. UNIQUE prevents duplicate WOs from the same Submit click.';

-- Partial unique index: NULL values (legacy rows) are not constrained
CREATE UNIQUE INDEX IF NOT EXISTS idx_work_orders_client_request_id
  ON public.work_orders (client_request_id)
  WHERE client_request_id IS NOT NULL;

-- 2) movements.client_request_id (used by Receiving and any other movement-creating flow)
ALTER TABLE public.movements
  ADD COLUMN IF NOT EXISTS client_request_id UUID;

COMMENT ON COLUMN public.movements.client_request_id IS
  'Per-submission UUID generated by the client. UNIQUE prevents duplicate movements from the same Submit click.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_movements_client_request_id
  ON public.movements (client_request_id)
  WHERE client_request_id IS NOT NULL;

COMMIT;
